name: PR Validation

on:
  pull_request:
    branches:
      - main

jobs:
    pr_validation:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - name: Setup Java
          uses: actions/setup-java@v4
          with:
            distribution: 'temurin'
            java-version: 17
        - name: Setup Gradle
          uses: gradle/actions/setup-gradle@v4
        - name: Build with Gradle
          run: ./gradlew check